config/routes.rb
Rails.application.routes.draw do
  resources :dogs
  root to: redirect('/people')
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: %i[ show edit update destroy ]

  # GET /dogs or /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1 or /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs or /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: "Dog was successfully created." }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1 or /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: "Dog was successfully updated." }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1 or /dogs/1.json
  def destroy
    @dog.destroy!

    respond_to do |format|
      format.html { redirect_to dogs_path, status: :see_other, notice: "Dog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dog_params
      params.require(:dog).permit(:name, :breed, :date_of_birth)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy!

    respond_to do |format|
      format.html { redirect_to people_path, status: :see_other, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :date_of_birth)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/dogs/_dog.html.erb
<div id="<%= dom_id dog %>">
  <p>
    <strong>Name:</strong>
    <%= dog.name %>
  </p>

  <p>
    <strong>Breed:</strong>
    <%= dog.breed %>
  </p>

  <p>
    <strong>Date of birth:</strong>
    <%= dog.date_of_birth %>
  </p>

</div>

app/views/dogs/_form.html.erb
<%= form_with(model: dog) do |form| %>
  <% if dog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
        <% dog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :breed, style: "display: block" %>
    <%= form.text_field :breed %>
  </div>

  <div>
    <%= form.label :date_of_birth, style: "display: block" %>
    <%= form.date_field :date_of_birth %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing dog</h1>

<%= render "form", dog: @dog %>

<br>

<div>
  <%= link_to "Show this dog", @dog %> |
  <%= link_to "Back to dogs", dogs_path %>
</div>

app/views/dogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dogs</h1>

<div id="dogs">
  <% @dogs.each do |dog| %>
    <%= render dog %>
    <p>
      <%= link_to "Show this dog", dog %>
    </p>
  <% end %>
</div>

<%= link_to "New dog", new_dog_path %>

app/views/dogs/new.html.erb
<h1>New dog</h1>

<%= render "form", dog: @dog %>

<br>

<div>
  <%= link_to "Back to dogs", dogs_path %>
</div>

app/views/dogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dog %>

<div>
  <%= link_to "Edit this dog", edit_dog_path(@dog) %> |
  <%= link_to "Back to dogs", dogs_path %>

  <%= button_to "Destroy this dog", @dog, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GitDemoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :date_of_birth, style: "display: block" %>
    <%= form.date_field :date_of_birth %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <strong>First name:</strong>
    <%= person.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= person.last_name %>
  </p>

  <p>
    <strong>Date of birth:</strong>
    <%= person.date_of_birth %>
  </p>

</div>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Show this person", @person %> |
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>People</h1>

<table>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td>
          <%= link_to "Show", person_path(person) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New person", new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person %>

<div>
  <%= link_to "Edit this person", edit_person_path(@person) %> |
  <%= link_to "Back to people", people_path %>

  <%= button_to "Delete this record", @person, method: :delete %>
</div>